// Generated by CoffeeScript 1.10.0
var GameState, Phaser, game, size_x, size_y;

Phaser = window.Phaser;

size_x = window.innerWidth;

size_y = window.innerHeight;

GameState = (function() {
  function GameState() {}

  GameState.prototype.update = function() {
    return null;
  };

  GameState.prototype.create = function() {
    this.game.stage.backgroundColor = "F88";
    return this.game.load.spritesheet('cat', 'images/cat_images/cat1.png', 37, 45, 18);
  };

  return GameState;

})();

game = new Phaser.Game(size_x, size_y);

game.state.add("Game", GameState, true);
