// Generated by CoffeeScript 1.10.0
(function() {
  var GameState, Phaser, game, size_x, size_y;

  Phaser = window.Phaser;

  size_x = window.innerWidth;

  size_y = window.innerHeight;

  GameState = (function() {
    function GameState() {}

    GameState.prototype.preload = function() {
      return this.game.load.image("cat", "/images/cat_images/cat17.png");
    };

    GameState.prototype.update = function() {
      this.player.body.velocity.x = 0;
      if (this.cursors.left.isDown) {
        this.player.body.velocity.x = -150;
      }
      if (this.cursors.right.isDown) {
        this.player.body.velocity.x = 150;
      }
      if (this.jumpButton.isDown && this.player.body.onFloor()) {
        return this.player.body.velocity.y = -250;
      }
    };

    GameState.prototype.create = function() {
      this.game.stage.backgroundColor = "8F8";
      game.physics.startSystem(Phaser.Physics.ARCADE);
      game.physics.arcade.gravity.y = 250;
      this.player = game.add.sprite(size_x / 2, size_y / 2, 'cat');
      this.player.height = 64;
      this.player.width = 64;
      game.physics.enable(this.player, Phaser.Physics.ARCADE);
      this.player.body.bounce.y = 0.5;
      this.player.body.collideWorldBounds = true;
      this.cursors = game.input.keyboard.createCursorKeys();
      return this.jumpButton = game.input.keyboard.addKey(Phaser.Keyboard.SPACEBAR);
    };

    return GameState;

  })();

  game = new Phaser.Game(size_x, size_y);

  game.state.add("Game", GameState, true);

}).call(this);
