// Generated by CoffeeScript 1.10.0
(function() {
  var GameState, Phaser, game, size_x, size_y;

  Phaser = window.Phaser;

  size_x = window.innerWidth;

  size_y = window.innerHeight;

  GameState = (function() {
    function GameState() {}

    GameState.prototype.update = function() {
      return null;
    };

    GameState.prototype.preload = function() {
      return game.load.image('cat', '/images/cat-cupid-love-icon2.png');
    };

    GameState.prototype.create = function() {
      game.stage.backgroundColor = "8FA";
      game.physics.startSystem(Phaser.Physics.ARCADE);
      this.emitter = game.add.emitter(0, 0, 1000);
      this.emitter.makeParticles('cat');
      this.emitter.gravity = 200;
      return game.input.onDown.add((function(_this) {
        return function(pointer) {
          _this.emitter.x = pointer.x;
          _this.emitter.y = pointer.y;
          return _this.emitter.start(true, 5000, null, 10);
        };
      })(this));
    };

    return GameState;

  })();

  game = new Phaser.Game(size_x, size_y);

  game.state.add("Game", GameState, true);

}).call(this);
