// Generated by CoffeeScript 1.10.0
(function() {
  var GameState, Phaser, game, randint, size_x, size_y;

  Phaser = window.Phaser;

  size_x = window.innerWidth;

  size_y = window.innerHeight;

  randint = function(a, b) {
    return a + Math.floor(Math.random() * (b - a));
  };

  GameState = (function() {
    function GameState() {
      null;
    }

    GameState.prototype.preload = function() {
      return this.game.load.image('cookie', '/images/cookie.png');
    };

    GameState.prototype.update = function() {
      var dt;
      dt = this.game.time.elapsed / 1000.0;
      if (this.cookie.x < 0 || this.cookie.x >= size_x - 120) {
        this.dx = -this.dx;
      }
      if (this.cookie.y < 0 || this.cookie.y >= size_y - 120) {
        this.dy = -this.dy;
      }
      this.cookie.x += this.dx * dt;
      return this.cookie.y += this.dy * dt;
    };

    GameState.prototype.create = function() {
      var angle, speed;
      this.game.stage.backgroundColor = "F8F";
      this.cookie = this.game.add.sprite(randint(0, size_x - 120), randint(0, size_y - 120), 'cookie');
      angle = Math.random() * 2 * Math.PI;
      speed = 200.0;
      this.dx = Math.cos(angle) * speed;
      return this.dy = Math.sin(angle) * speed;
    };

    return GameState;

  })();

  game = new Phaser.Game(size_x, size_y);

  game.state.add("Game", GameState, true);

}).call(this);
