// Generated by CoffeeScript 1.10.0
(function() {
  var GameState, Phaser, create, game, game_state, size_x, size_y, update;

  Phaser = window.Phaser;

  game_state = null;

  size_x = window.innerWidth;

  size_y = window.innerHeight;

  GameState = (function() {
    function GameState() {
      null;
    }

    GameState.prototype.update = function(dt) {
      return null;
    };

    return GameState;

  })();

  update = function() {
    return game_state.update(game.time.elapsed / 1000.0);
  };

  create = function() {
    return game.stage.backgroundColor = "88F";
  };

  game_state = new GameState;

  game = new Phaser.Game(size_x, size_y, Phaser.AUTO, '', {
    create: create,
    update: update
  });

}).call(this);
