// Generated by CoffeeScript 1.10.0
(function() {
  var Board, GameState, Phaser, Tile, game, shuffle, size_x, size_y,
    slice = [].slice;

  Phaser = window.Phaser;

  size_x = window.innerWidth;

  size_y = window.innerHeight;

  shuffle = function(a) {
    var i, j, t;
    i = a.length;
    while (--i > 0) {
      j = ~~(Math.random() * (i + 1));
      t = a[j];
      a[j] = a[i];
      a[i] = t;
    }
    return a;
  };

  Tile = (function() {
    function Tile(x, y, c) {
      this.x = x;
      this.y = y;
      this.c = c;
      this.status = "hidden";
      this.bg = game.add.graphics(this.x, this.y);
      this.bg.lineStyle(2, 0x000000, 1);
      this.bg.beginFill(0xFF8888);
      this.bg.drawPolygon(-48, -48, -48, 48, 48, 48, 48, -48, -48, -48);
      this.tile = game.add.sprite(this.x, this.y, "cat" + c);
      this.tile.anchor.setTo(0.5, 0.5);
      this.tile.height = 96;
      this.tile.width = 96;
      this.tile.visible = false;
      this.hidden_tile = game.add.text(this.x, this.y, "?");
      this.hidden_tile.anchor.setTo(0.5, 0.5);
    }

    Tile.prototype.set_status = function(status) {
      this.status = status;
      switch (status) {
        case "hidden":
          this.tile.visible = false;
          return this.hidden_tile.visible = true;
        case "peek":
        case "revealed":
          this.tile.visible = true;
          return this.hidden_tile.visible = false;
      }
    };

    return Tile;

  })();

  Board = (function() {
    function Board() {
      var tiles, x, y;
      this.size_x = 6;
      this.size_y = 6;
      tiles = shuffle(slice.call([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]).concat(slice.call([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])));
      this.content = (function() {
        var k, ref, results;
        results = [];
        for (x = k = 0, ref = this.size_x; 0 <= ref ? k < ref : k > ref; x = 0 <= ref ? ++k : --k) {
          results.push((function() {
            var l, ref1, results1;
            results1 = [];
            for (y = l = 0, ref1 = this.size_y; 0 <= ref1 ? l < ref1 : l > ref1; y = 0 <= ref1 ? ++l : --l) {
              results1.push(tiles.pop());
            }
            return results1;
          }).call(this));
        }
        return results;
      }).call(this);
      this.setup_grid();
      this.status = "ready";
    }

    Board.prototype.setup_grid = function() {
      var loc_x, loc_y, x, y;
      return this.grid = (function() {
        var k, ref, results;
        results = [];
        for (x = k = 0, ref = this.size_x; 0 <= ref ? k < ref : k > ref; x = 0 <= ref ? ++k : --k) {
          results.push((function() {
            var l, ref1, results1;
            results1 = [];
            for (y = l = 0, ref1 = this.size_y; 0 <= ref1 ? l < ref1 : l > ref1; y = 0 <= ref1 ? ++l : --l) {
              loc_x = (size_x / 2 - 96 * 2.5) + 96 * x;
              loc_y = (size_y / 2 - 96 * 2.5) + 96 * y;
              results1.push(new Tile(loc_x, loc_y, this.content[x][y]));
            }
            return results1;
          }).call(this));
        }
        return results;
      }).call(this);
    };

    Board.prototype.click_cell = function(x, y) {
      if (this.grid[x][y].status === "revealed") {
        return false;
      }
      switch (this.status) {
        case "ready":
          this.grid[x][y].set_status("peek");
          this.x1 = x;
          this.y1 = y;
          this.status = "one";
          return false;
        case "one":
          if (x === this.x1 && y === this.y1) {
            return false;
          } else if (this.grid[x][y].c === this.grid[this.x1][this.y1].c) {
            this.grid[this.x1][this.y1].set_status("revealed");
            this.grid[x][y].set_status("revealed");
            this.status = "ready";
            return true;
          } else {
            this.grid[x][y].set_status("peek");
            this.x2 = x;
            this.y2 = y;
            this.status = "two";
            return true;
          }
          break;
        case "two":
          this.grid[this.x1][this.y1].set_status("hidden");
          this.grid[this.x2][this.y2].set_status("hidden");
          this.status = "ready";
          this.click_cell(x, y);
          return false;
      }
    };

    return Board;

  })();

  GameState = (function() {
    function GameState() {}

    GameState.prototype.preload = function() {
      var i, k, results;
      results = [];
      for (i = k = 1; k <= 18; i = ++k) {
        results.push(this.game.load.image("cat" + i, "/images/cat_images/cat" + i + ".png"));
      }
      return results;
    };

    GameState.prototype.update = function() {
      return this.scoreText.text = "Clicks: " + this.score;
    };

    GameState.prototype.click = function(x, y) {
      x = Math.round((x - size_x / 2 + 96 * 2.5) / 96);
      y = Math.round((y - size_y / 2 + 96 * 2.5) / 96);
      if (x >= 0 && x <= this.board.size_x - 1 && y >= 0 && y <= this.board.size_y - 1) {
        if (this.board.click_cell(x, y)) {
          return this.score += 1;
        }
      }
    };

    GameState.prototype.create = function() {
      this.score = 0;
      this.scoreText = game.add.text(16, 16, '', {
        fontSize: '32px',
        fill: '#fff'
      });
      this.game.stage.backgroundColor = "88F";
      this.board = new Board;
      return this.game.input.onTap.add((function(_this) {
        return function() {
          return _this.click(_this.game.input.activePointer.worldX, _this.game.input.activePointer.worldY);
        };
      })(this));
    };

    return GameState;

  })();

  game = new Phaser.Game(size_x, size_y);

  game.state.add("Game", GameState, true);

}).call(this);
