// Generated by CoffeeScript 1.10.0
var GameState, Phaser, game, size_x, size_y;

Phaser = window.Phaser;

size_x = window.innerWidth;

size_y = window.innerHeight;

GameState = (function() {
  function GameState() {
    null;
  }

  GameState.prototype.update = function() {
    var dt;
    dt = this.game.time.elapsed / 1000.0;
    if (game.input.keyboard.isDown(Phaser.KeyCode.W)) {
      this.left_paddle.y -= dt * 600;
    }
    if (game.input.keyboard.isDown(Phaser.KeyCode.S)) {
      this.left_paddle.y += dt * 600;
    }
    if (game.input.keyboard.isDown(Phaser.KeyCode.UP)) {
      this.right_paddle.y -= dt * 600;
    }
    if (game.input.keyboard.isDown(Phaser.KeyCode.DOWN)) {
      return this.right_paddle.y += dt * 600;
    }
  };

  GameState.prototype.create = function() {
    var i, ref, ref1, y;
    this.game.stage.backgroundColor = "FFFF00";
    this.grid = game.add.graphics(size_x / 2, size_y / 2);
    this.grid.lineStyle(5, "white");
    for (y = i = ref = -size_y / 2, ref1 = size_y / 2; i <= ref1; y = i += 20) {
      this.grid.moveTo(0, y);
      this.grid.lineTo(0, y + 10);
    }
    this.left_score = game.add.text(size_x / 4, size_y / 8, 'kittens', {
      fontSize: '100px',
      fill: '#000',
      align: "center"
    });
    this.left_score.anchor.set(0.5);
    this.right_score = game.add.text(size_x / 4 * 3, size_y / 8, 'puppies', {
      fontSize: '100px',
      fill: '#000',
      align: "center"
    });
    this.right_score.anchor.set(0.5);
    this.left_paddle = game.add.graphics(10, size_y / 2);
    this.left_paddle.lineStyle(5, "white");
    this.left_paddle.lineStyle(0);
    this.left_paddle.beginFill(0x000);
    this.left_paddle.drawRect(0, -65, 30, 130);
    this.right_paddle = game.add.graphics(size_x - 40, size_y / 2);
    this.right_paddle.lineStyle(5, "white");
    this.right_paddle.lineStyle(0);
    this.right_paddle.beginFill(0x000);
    return this.right_paddle.drawRect(0, -65, 30, 130);
  };

  return GameState;

})();

game = new Phaser.Game(size_x, size_y);

game.state.add("Game", GameState, true);
