// Generated by CoffeeScript 1.10.0
(function() {
  var GameState, Phaser, game, size_x, size_y;

  Phaser = window.Phaser;

  size_x = window.innerWidth;

  size_y = window.innerHeight;

  GameState = (function() {
    function GameState() {
      null;
    }

    GameState.prototype.interpolate_angle = function(distance, angle_ratio) {
      var a, x, y;
      x = size_x / 2 + distance * Math.sin(Math.PI * 2 * angle_ratio);
      y = size_y / 2 - distance * Math.cos(Math.PI * 2 * angle_ratio);
      a = 360 * angle_ratio;
      return [x, y, a];
    };

    GameState.prototype.hour_text = function(i) {
      var angle, label, ref, text, x, y;
      ref = this.interpolate_angle(200, i / 24), x = ref[0], y = ref[1], angle = ref[2];
      label = "" + i;
      text = new Phaser.Text(game, x, y, label, {
        font: "20px Arial",
        fill: "#ff0044",
        align: "center"
      });
      text.anchor.set(0.5);
      text.angle = angle;
      return game.add.existing(text);
    };

    GameState.prototype.minute_text = function(i) {
      var angle, label, ref, text, x, y;
      ref = this.interpolate_angle(275, i / 60), x = ref[0], y = ref[1], angle = ref[2];
      label = "" + i;
      text = new Phaser.Text(game, x, y, label, {
        font: "20px Arial",
        fill: "#ff0044",
        align: "center"
      });
      text.anchor.set(0.5);
      text.angle = angle;
      return game.add.existing(text);
    };

    GameState.prototype.second_text = function(i) {
      var angle, label, ref, text, x, y;
      ref = this.interpolate_angle(350, i / 60), x = ref[0], y = ref[1], angle = ref[2];
      label = "" + i;
      text = new Phaser.Text(game, x, y, label, {
        font: "20px Arial",
        fill: "#ff0044",
        align: "center"
      });
      text.anchor.set(0.5);
      text.angle = angle;
      return game.add.existing(text);
    };

    GameState.prototype.update = function() {
      return null;
    };

    GameState.prototype.create = function() {
      var i;
      this.game.stage.backgroundColor = "88F";
      this.hours = (function() {
        var j, results;
        results = [];
        for (i = j = 0; j <= 23; i = ++j) {
          results.push(this.hour_text(i));
        }
        return results;
      }).call(this);
      this.minutes = (function() {
        var j, results;
        results = [];
        for (i = j = 0; j <= 59; i = ++j) {
          results.push(this.minute_text(i));
        }
        return results;
      }).call(this);
      return this.seconds = (function() {
        var j, results;
        results = [];
        for (i = j = 0; j <= 59; i = ++j) {
          results.push(this.second_text(i));
        }
        return results;
      }).call(this);
    };

    return GameState;

  })();

  game = new Phaser.Game(size_x, size_y);

  game.state.add("Game", GameState, true);

}).call(this);
